name: Auto Merge Dependency Updates

on:
  - pull_request

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1
        with:
          allowed-actors: allcontributors[bot], all-contributors-preview[bot]
